### ISSUE TITLE
Would be good; if you give suggestions on Decorator Based Validation 

### ISSUE THREAD

**Issue by ajayojha** [rxweb/rxweb#137]
If you are using decorator based validation approach in your application. 

I would like know your suggestions on decorator based validation to help to make our framework better.  

* What are the challenges you are facing with this approach?
* How to make this more easier in development?
* What are the new functionality we can add in this to help in your application as well as others?
* What are the bottleneck you see with this approach, which we have to consider first?
* Feel free to share your thoughts which is not covered in my questions.

awaiting for your response 😄

**Comment by sholkajadav11** [comment]
The library is amazing. Thanks for the taking feedback from the users who are using this.

It is difficult to maintain the code in the html to show the error messages in the HTML.
Currently I am writing below code as per your suggestion on gitter to someone else : 

```html
<input type="text" formControlName="bankName" />
{{bankGroup.controls.bankName["errorMessage"]}}
```
The above code is pretty annoying for me because once I forgot to write the code as per above then it gives error when I execute build prod command.

I would suggest please provide the feature same as like we use AbstractControl properties.

My suggestion would be something like below :

```html
<input type="text" formControlName="bankName" />
{{bankGroup.controls.bankName.errorMessage}}
```

**Comment by ajayojha** [comment]
Thanks for the suggestion, It's in my plan. But was on low priority. Now I will try to release this in the first or second release.
