### ISSUE TITLE
Add new Clear Input decorator

### ISSUE THREAD

**Issue by tsaatey** [rxweb/rxweb#158]
### Description

A decorator that can clear an input field based on a condition

### Describe the solution you'd like
I would like a decorator named @clear, just like @required or any other that takes a conditional expression and clears content in the input field based on the condition. For example, I have a radio button that enables or disables an input field using true or false values. If I want to be tricky, I can enable the input field, enter a value and then disable it. This clear feature should be able to clear whatever I have entered once I disable the input field after inputting something in it

**Comment by ajayojha** [comment]
@tsaatey Thanks for this ticket. I am thinking, it is more elegant if we add a new property(**OnDisableClean**) in the @disable decorator. Whenever the FormControl will be disabled at that time cleared the value if **OnDisableClean** value is true.

The benefit of using this is you don't need to use two decorators.

Share your inputs...

**Comment by tsaatey** [comment]
Oh cool! I like the idea.

**Comment by ajayojha** [comment]
I appreciate your suggestion of @clear decorator, do you think clear decorator will help in some other scenarios.

**Comment by ajayojha** [comment]
While working on this feature request. I realized that we don't need to add the extra property in the ```DisableConfig``` or to create the @clear decorator. Because clear value can be done through setter property of the model.

How this can be achieved through setter property, that is describing as below:

As per your scenario, I have created a ```User``` model with two properties of ```freeText``` and ```shouldDisable```. ```shouldDisable``` property defines as getter/setter property. The benefit of using this is whenever we change the value through UI, It will automatically call the setter method of ```shouldDisable```.
Here is the ```User``` model.
```js
export class User {
    _shouldDisable: boolean;

    @disable({ conditionalExpression: function () { return this.shouldDisable == true } })
    @prop()
    freeText: string;

    @toBoolean()
    @prop()
    set shouldDisable(value: boolean) {
        this._shouldDisable = value;
        if (value)
            this.freeText = undefined;
    }

    @prop()
    viewType: string;

    get shouldDisable() {
        return this._shouldDisable;
    }

}
```
Whenever the ```shouldDisable``` called, it clears the value of freeText if the value is true.

Please refer to the stackblitz example and test it as per your scenario: https://stackblitz.com/edit/clear-formcontrol-value?file=src%2Fapp%2Fuser-info%2Fadd%2Fuser.model.ts

Feel free to share your suggestions.

**Comment by ajayojha** [comment]
I am closing this ticket because of no further action required on this. Feel free create the new ticket if you have a solid reason to add clear decorator in the framework.
