### ISSUE TITLE
Validators not working with ng-zorro

### ISSUE THREAD

**Issue by j0nm1** [rxweb/rxweb#218]
## Describe the problem statement?
Hi,
I used rxweb in several other projects and found the validators really helpful. In a new project, I have to use ng-zorro (https://ng.ant.design/components/form/en) and would like to use the validators again, but sadly this does not work. The "required" validator works, but the "email" one does not when I'm trying to validate the inputs on submit. 
When I'm typing in the field, the validation works just fine but I need to validate the inputs while calling a method.

## The expected solution you would like
There should be a way to validate the controls when pressing submit.

## Url
This demo shows the problem. When pressing "Login", the "required" validator shows the error text but the "email" validator does nothing (like every other validator that I have tested)

https://stackblitz.com/edit/ng-zorro-antd-start-z7fmvc

## Package version
latest

**Comment by ajayojha** [comment]
@j0nm1 Thank You for sharing the detailed information. The provided example is working as expected because the email validator won't work if no value exists in the control. For that you have to use 'required' validator, the email validator only works when you have entered a wrong input.

Please let me know if you have any question.

**Comment by ajayojha** [comment]
I hope your concern has been resolved with my previous comment. I am closing this ticket, feel free to open a new ticket if you have any question.
