### ISSUE TITLE
Tool-tip

### ISSUE THREAD

**Issue by rxdotnetdev2** [rxweb/rxweb#330]
Hello @ajayojha sir. 

I have been using @rxweb's packages but I guesss there is an unavailability of the tool-tip or I am not aware of the latest package and as our requirement we must need to add this feature in out project.

So it's a request, please provide us this feature so we can easily implement it.

Please let me know for the solution of this feature.

**Comment by ajayojha** [comment]
@rxdotnetdev2  right now there is no plan to add tooltip feature in the lib, if it's an immediate need then I would suggest you some third party library for tooltip.

**Comment by rxdotnetdev2** [comment]
Hello @ajayojha sir, Thanks for your reply in a nice way.

It would be great if you suggest a third-party library or jquery to implement tool-tip.

**Comment by ajayojha** [comment]
Please refer bootstrap tooltip library

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rxdotnetdev2** [comment]
One more query sir, after your suggestion will it affect our architecture code means it will be easily added without disturb any existing code?

**Comment by ajayojha** [comment]
You have to do some research on that part 🙂. Or else wait for 7 days because there are so many things in our hand and no chance to draft the business case document, after 7 days will let you when we can this feature in our lib.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
