### ISSUE TITLE
More Than One Inline Date Picker Not Binding Properly 

### ISSUE THREAD

**Issue by Kiran-Pawar** [rxweb/rxweb#388]
## Description
I have to use two inline rx-date pickers in rx-grid one for Start Data and another for End Date and need to perform edit operation in grid.I have took reference of ticket #343 and able to bind single date picker in grid successfully.To use two inline rx-date picker I have created two classes in app-grid.ts(SelectStartDate and SelectEndDate).But problem is it is not binding second rx-date picker in proper sequence  For e.g :  end date of 2nd record gets bind in 1st record and getting error "cannot read property 'startDate' of undefined" .I have to complete this task before 21/08/2020.so can you please help me out in this.

## Expected Behavior
     It should bind more than one inline rx-date pickers properly in grid 
## Url
Here I am sharing stackblitz url:- https://stackblitz.com/edit/angular-uhqgns?file=src%2Fapp%2Fapp.component.html
## Package version
@rxweb/grid@0.0.2-beta8

**Comment by ajayojha** [comment]
@Kiran-Pawar , Please refer to this updated [stackblitz example](https://stackblitz.com/edit/rxweb-grid-with-datepicker?file=src/app/app-grid.ts).
There was an issue in the implemented code, here are findings:
* You don't need to implement increment manually, without this can be achieved because you are getting the current row object in the second parameter of the method ```resolveOnDemandSelector```.
* You don't need to put 'if' clauses for creating a date control column-wise, please use the same class.

Please refer to the updated code.
