### ISSUE TITLE
How to show nested form error in template ?

### ISSUE THREAD

**Issue by bharat-dpd** [rxweb/rxweb#57]
# Description

How can I show the error message for the nested form group? I tried some example but no luck with that. Can someone please have a look at
[stackblitz](https://stackblitz.com/edit/angular-9m6xza?file=src%2Fapp%2Fapp.component.html)

**Comment by ajayojha** [comment]
let me check and let you know.

**Comment by ajayojha** [comment]
This is the working link of stackblitz : https://stackblitz.com/edit/angular-1qtxjj?file=src/app/app.component.html .
There were two problems in the HTML:
**Earlier**
``
[formGroup]="userInfoFormGroup.address" 
``
**Now**
``
[formGroup]="userInfoFormGroup.controls.address"
``
Second problem was :
**Earlier**
``
{{address.controls.city.errorMessage}}
``
**Now**
``
{{userInfoFormGroup.controls.address.controls.city.errorMessage}}
``

Please let me know, if you any question.

**Comment by bharat-dpd** [comment]
@ajayojha Thanx Ajay.  I was following your gist. Now I got the point where I was doing the mistake.

**Comment by ajayojha** [comment]
One more thing I would suggest try to use errorMessage property like this way 'address.controls.city["errorMessage"]', because abstract control doesn't have a property of errorMessage and when you fire ng build --prod then it gives an error. So better to write 'address.controls.city["errorMessage"]'. I have updated the stackblitz url also: https://stackblitz.com/edit/angular-1qtxjj?file=src/app/app.component.html

**Comment by bharat-dpd** [comment]
Thanks, @ajayojha for your valuable tip. I will keep this in my mind. BTW great job on validation part. I am producing one more case with number type of validation. I will share the stackblitz link with you very soon.

**Comment by ajayojha** [comment]
Your welcome, I would suggest please come on Gitter. So That I can help you quickly. This is link https://gitter.im/rxweb-project/rxweb .

**Comment by ajayojha** [comment]
I am closing this issue as no further action required on this.
